checking the CI/CD for Web Application

diff --git a/.github/workflows/image.yml b/.github/workflows/image.yml
--- a/.github/workflows/image.yml
+++ b/.github/workflows/image.yml
@@ -1,5 +1,5 @@
 on:
-  pull_request:
+  push:
     branches:
      - main
 
@@ -78,7 +78,7 @@ jobs:
           AWS_DEFAULT_REGION: us-east-1
 
       - name:  Setting up demo environment
-        uses: aws-actions/configure-aws-credentials@v1
+        uses: aws-actions/configure-aws-credentials@v2
         with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEMO}}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEMO}}
@@ -92,4 +92,23 @@ jobs:
   
       - name: Instance Refresh in autoscaling group
         run: "aws autoscaling start-instance-refresh --auto-scaling-group-name ${{ secrets.AUTO_SCALING_GROUP_NAME }}"
+
+      - name: Wait for Instance Refresh to Complete
+        run: |
+          REFRESH_STATUS="InProgress"
+          while [ "$REFRESH_STATUS" == "InProgress" ]; do
+            echo "Waiting for instance refresh to complete..."
+            REFRESH_STATUS=$(aws autoscaling describe-instance-refreshes \
+              --auto-scaling-group-name ${{ secrets.AUTO_SCALING_GROUP_NAME }} \
+              --query 'InstanceRefreshes[0].Status' \
+              --output text)
+            sleep 30  # Wait for 30 seconds before checking again
+          done
+
+          if [ "$REFRESH_STATUS" == "Successful" ]; then
+            echo "Instance refresh completed successfully."
+          else
+            echo "Instance refresh failed."
+            exit 1  # Fail the workflow if the refresh was not successful
+          fi
      
